### ISSUE TITLE
How does this compare with axe?

### ISSUE THREAD

**Issue by mgifford** [p1ho/accessibility-checker#7]
Curious how this compares with axe.

**Comment by p1ho** [comment]
Hello, disclaimer, Axe is actively being worked on with a dedicated team, so in terms of accessibility compliance, they are going to be more up to date. I'm not actively working on this project, so aspects of it may be outdated.

This was something I used for Drupal where content is templatized, this means part of the html is generated by Drupal, and part of it from your content. If you use Axe for Drupal sites, it might give you errors/warnings about things you don't have control over like Navbar, footer, etc.

This is useful for Wordpress/Drupal sites where there is a separation of concern between template engine and content, and you can focus on accessibility issues with content.

**Comment by mgifford** [comment]
No worries.  

Might worth taking a look at https://ryersondmp.github.io/sa11y/ & for Drupal https://www.drupal.org/project/editoria11y & https://www.drupal.org/project/ckeditor_accessibility_auditor are worth looking at. 

None of them are using Axe at this point, but axe could be customized to focus more specifically and use custom rulesets.

I'm not sure if there is something similar for WP.

Thanks for your feedback and work on this. I hate folks duplicating efforts.
